---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: eatups
  name: dev-team-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "deployments"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-team-binding
  namespace: eatups
subjects:
- kind: Group
  name: dev-team
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: tobe
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: vera
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: dev-team-role
  apiGroup: rbac.authorization.k8s.io
---
